'use strict';

export enum StairCaseCommand {
  BRANCH_DIFFERENT              = '!',
  BRANCH_EQUAL                  = '=',
  BRANCH_GREATER                = '>',
  BRANCH_LESS                   = '<',
  BRANCH_UNCONDITIONAL          = ':',
  COMMENT                       = ';',
  COPY_CELL                     = '@',
  INPUT_NUMBER                  = '$',
  INPUT_STRING_WITH_SIZE        = '?',
  INPUT_STRING_WITHOUT_SIZE     = '_',
  LITERAL_NUMBER                = '`',
  LITERAL_STRING                = '\\',
  OPERATION_BITWISE_AND         = '&',
  OPERATION_BITWISE_OR          = '|',
  OPERATION_BITWISE_SHIFT_LEFT  = '{',
  OPERATION_BITWISE_SHIFT_RIGHT = '}',
  OPERATION_BITWISE_XOR         = '^',
  OPERATION_DIVIDE              = '/',
  OPERATION_MODULO              = '%',
  OPERATION_MULTIPLY            = '*',
  OPERATION_NOT                 = '~',
  OPERATION_SUBTRACT            = '-',
  OPERATION_SUM                 = '+',
  PRINT_NUMBER_WITH_EOL         = '"',
  PRINT_NUMBER_WITHOUT_EOL      = '#',
  PRINT_STRING_WITH_EOL         = '.',
  PRINT_STRING_WITHOUT_EOL      = ',',
  RANDOM                        = '\'',
  ROUND                         = ')',
  SUBROUTINE_CALL               = '[',
  SUBROUTINE_RETURN             = ']',
  TRUNCATE                      = '('
};
